# Numpy

In [65]:
import numpy as np

## Numpy Methods

### Creating an array

In [6]:
lst = [1, 2, 3, 4, 5]
type(lst)

list

In [10]:
arr = np.array(lst)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

### Arange

In [12]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(0, 11, 2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [15]:
arr = np.arange(0.5, 10.5, 0.5)
arr

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### linsplace

In [3]:
arr = np.linspace(10, 20, 10)
print(arr)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


### Zeroes And ones

#### Zeroes

In [20]:
zeros_arr1 = np.zeros(4)
zeros_arr2 = np.zeros((4, 3))
print(zeros_arr1)
print("-----")
print(zeros_arr2)

[0. 0. 0. 0.]
-----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones

In [21]:
ones_arr1 = np.ones(4)
ones_arr2 = np.ones((4, 3))
print(ones_arr1)
print("-----")
print(ones_arr2)

[1. 1. 1. 1.]
-----
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Indentity (eye)

In [24]:
eye_arr = np.eye(4)
print(eye_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Diagonal

In [29]:
diag_arr1 = np.diag([1, 2, 3, 4])
diag_arr2 = np.diag((5, 6, 7, 8))
print(diag_arr1)
print('-----')
print(diag_arr2)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
-----
[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


### Tril and Triu

In [32]:
tril_arr = np.tril([1, 2, 3, 4])
triu_arr = np.triu([1, 2, 3, 4])
print("Tril")
print(tril_arr)
print("-----")
print("Triu")
print(triu_arr)

Tril
[[1 0 0 0]
 [1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]
-----
Triu
[[1 2 3 4]
 [0 2 3 4]
 [0 0 3 4]
 [0 0 0 4]]


### Random

In [55]:
rand_arr1 = np.random.rand(4)
print(rand_arr1)
print("-----")

rand_arr2 = np.random.random(4)
print(rand_arr2)
print("-----")

rand_arr3 = np.random.random((3, 4))
print(rand_arr3)
print("----------")

rand_arr4 = np.random.randint(1, 10)
print(rand_arr4)
print("----------")

rand_arr5 = np.random.randint(20, 30, (3, 4))
print(rand_arr5)
print("----------")

[0.70000605 0.49213888 0.73236126 0.44155521]
-----
[0.06700191 0.95359046 0.54075965 0.70923811]
-----
[[0.73730411 0.9597152  0.93078011 0.38205631]
 [0.50738226 0.00441154 0.08287105 0.93050428]
 [0.30314027 0.7512728  0.12502739 0.21945308]]
----------
5
----------
[[25 25 29 26]
 [26 20 22 26]
 [22 29 20 23]]
----------


### Reshape

In [59]:
arr = np.random.random(10)
print(arr)
print("----------")

reshape_arr = arr.reshape((5, 2))
print(reshape_arr)
print("----------")

reshape_arr2 = arr.reshape((2, 5))
print(reshape_arr2)
print("----------")

arr2 = np.random.random(10).reshape((5, 2))
print(arr2)
print("----------")

[0.56137222 0.42447644 0.70867407 0.75618446 0.09000953 0.13718432
 0.44888979 0.54617453 0.96209079 0.77998192]
----------
[[0.56137222 0.42447644]
 [0.70867407 0.75618446]
 [0.09000953 0.13718432]
 [0.44888979 0.54617453]
 [0.96209079 0.77998192]]
----------
[[0.56137222 0.42447644 0.70867407 0.75618446 0.09000953]
 [0.13718432 0.44888979 0.54617453 0.96209079 0.77998192]]
----------
[[0.63117518 0.8787365 ]
 [0.92438173 0.51979988]
 [0.33265321 0.77368167]
 [0.19278878 0.81979297]
 [0.53855092 0.73596604]]
----------


### Mathematical and statistical operations

#### Sum, Min, Max, Argmin, Argmax

In [42]:
rand_arr = np.random.randint(1, 20, 10)
print(rand_arr)
print("----------")

print("Max: ", max(rand_arr))
print("Min: ", np.max(rand_arr))
print("Min: ", min(rand_arr))
print("Min: ", np.min(rand_arr))
print("----------")

print(f"Sum: {sum(rand_arr)}")
print(f"Sum: {np.sum(rand_arr)}")
print("----------")

print(f"Argmin: {np.argmin(rand_arr)}")
print("----------")

print(f"Argmax: {np.argmax(rand_arr)}")

[10  5 13 11  8 10 10  8 12  5]
----------
Max:  13
Min:  13
Min:  5
Min:  5
----------
Sum: 92
Sum: 92
----------
Argmin: 1
----------
Argmax: 2


#### add, subtract, multiply, divide, power

In [52]:
rand_arr = np.random.randint(1, 20, 10)
print("add")
print(np.add(rand_arr, 1000))
print("----------\n")

print("subtract")
print(np.subtract(rand_arr, 1000))
print("----------\n")

print("Multiply")
print(np.multiply(rand_arr, 1000))
print("----------\n")

print("Divide")
print(np.divide(rand_arr, 1000))
print("----------\n")

print("Power")
print(np.power(rand_arr, 2))
print("----------\n")


add
[1018 1011 1001 1010 1004 1013 1014 1010 1016 1002]
----------

subtract
[-982 -989 -999 -990 -996 -987 -986 -990 -984 -998]
----------

Multiply
[18000 11000  1000 10000  4000 13000 14000 10000 16000  2000]
----------

Divide
[0.018 0.011 0.001 0.01  0.004 0.013 0.014 0.01  0.016 0.002]
----------

Power
[324 121   1 100  16 169 196 100 256   4]
----------



#### std, var, mean

##### Mean

In [53]:
array = np.arange(1, 22).reshape(3, 7)
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [56]:
print("mean of all elements")
print(np.mean(array))
print("----------\n")

print("mean per row --> (axis=1)")
print(np.mean(array, axis=1))
print("----------\n")

print("mean per column --> (axis=0)")
print(np.mean(array, axis=0))
print("----------\n")

mean from all of array
11.0
----------

mean from axis 1 --> x axis
[ 4. 11. 18.]
----------

mean from axis 0 --> y axis
[ 8.  9. 10. 11. 12. 13. 14.]
----------



##### Variance

In [57]:
print("variance of all elements")
print(np.var(array))
print("----------\n")

print("variance per row (axis=1)")
print(np.var(array, axis=1))
print("----------\n")

print("variance per column (axis=0)")
print(np.var(array, axis=0))
print("----------\n")

variance from all of array
36.666666666666664
----------

variance from axis 1 --> x axis
[4. 4. 4.]
----------

variance from axis 0 --> y axis
[32.66666667 32.66666667 32.66666667 32.66666667 32.66666667 32.66666667
 32.66666667]
----------



##### standard deviation

In [58]:
print("standard deviation of all elements")
print(np.std(array))
print("----------\n")

print("standard deviation per row (axis=1)")
print(np.std(array, axis=1))
print("----------\n")

print("standard deviation per column (axis=0)")
print(np.std(array, axis=0))
print("----------\n")

standard deviation of all elements
6.0553007081949835
----------

standard deviation per row (axis=1)
[2. 2. 2.]
----------

standard deviation per column (axis=0)
[5.71547607 5.71547607 5.71547607 5.71547607 5.71547607 5.71547607
 5.71547607]
----------



#### sqrt, log, exp, sin, cos, pi, ...

In [81]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [83]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [84]:
np.exp(array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [86]:
np.pi

3.141592653589793

In [85]:
np.sin(np.pi)

np.float64(1.2246467991473532e-16)

### concatinate, vstack, hstack

In [41]:
arr1 = np.random.randint(6, 10, (3, 4))
arr2 = np.random.randint(1, 5, (3, 4))
print(arr1)
print("--------")
print(arr2)
print("----------")

print("Vstack")
arr3 = np.vstack([arr1, arr2])
print(arr3)
print("----------")

print("hstack")
arr4 = np.hstack([arr1, arr2])
print(arr4)
print("----------")

print("concatenate")
print("Axis = 0")
arr5 = np.concatenate((arr1, arr2), axis=0)
print(arr5)

print("----------")
print("Axis = 1")
arr6 = np.concatenate((arr1, arr2), axis=1)
print(arr6)

[[8 6 7 7]
 [7 8 7 6]
 [7 8 9 6]]
--------
[[1 2 3 4]
 [3 4 2 1]
 [1 4 1 4]]
----------
Vstack
[[8 6 7 7]
 [7 8 7 6]
 [7 8 9 6]
 [1 2 3 4]
 [3 4 2 1]
 [1 4 1 4]]
----------
hstack
[[8 6 7 7 1 2 3 4]
 [7 8 7 6 3 4 2 1]
 [7 8 9 6 1 4 1 4]]
----------
concatenate
Axis = 0
[[8 6 7 7]
 [7 8 7 6]
 [7 8 9 6]
 [1 2 3 4]
 [3 4 2 1]
 [1 4 1 4]]
----------
Axis = 1
[[8 6 7 7 1 2 3 4]
 [7 8 7 6 3 4 2 1]
 [7 8 9 6 1 4 1 4]]


### Ravel, flatten

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.ravel(array)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy Attribute

#### dtype, size, ndim, shape, ravel

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array.dtype

dtype('int64')

In [4]:
array.size

9

In [5]:
array.ndim

2

In [6]:
array.shape

(3, 3)

In [87]:
array.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Numpy indexing & Slicing

In [59]:
array = np.random.randint(1, 10, (3, 4))
array

array([[7, 5, 1, 5],
       [5, 4, 8, 9],
       [9, 6, 1, 9]])

In [60]:
# array[start=0:stop-1=last:step=1]
array[0:3, 0:2]

array([[7, 5],
       [5, 4],
       [9, 6]])

In [61]:
array[::, ::]

array([[7, 5, 1, 5],
       [5, 4, 8, 9],
       [9, 6, 1, 9]])

In [64]:
array[1:3, 1:3]

array([[4, 8],
       [6, 1]])

In [63]:
array[1:3, 2:4]

array([[8, 9],
       [1, 9]])

## Broadcasting

In [15]:
lst = [62, 82, 71, 74, 69, 97, 13, 82, 17, 93]
lst

[62, 82, 71, 74, 69, 97, 13, 82, 17, 93]

In [16]:
# Error
lst[5:10] = 100

TypeError: must assign iterable to extended slice

In [17]:
lst[5:10] = [100]

In [18]:
lst

[62, 82, 71, 74, 69, 100]

In [25]:
lst[5:10] = 100, 100, 100, 100, 100

In [24]:
lst

[62, 82, 71, 74, 69, 100, 100, 100, 100, 100, 100]

In [26]:
arr = np.random.randint(1, 100, 10)
arr

array([69, 50, 27, 26, 95, 69, 19, 36, 44, 13])

In [27]:
arr[5:10] = 100

In [28]:
arr

array([ 69,  50,  27,  26,  95, 100, 100, 100, 100, 100])

### Copy

In [29]:
new_arr = arr[5:10]
new_arr

array([100, 100, 100, 100, 100])

In [30]:
new_arr[::] = -10
new_arr

array([-10, -10, -10, -10, -10])

In [31]:
arr

array([ 69,  50,  27,  26,  95, -10, -10, -10, -10, -10])

In [32]:
new_arr2 = arr[5:10].copy()

In [33]:
new_arr2[::] = -100

In [34]:
arr

array([ 69,  50,  27,  26,  95, -10, -10, -10, -10, -10])

In [35]:
new_arr2

array([-100, -100, -100, -100, -100])

## Numpy Operation

### Arithmetic

In [66]:
arr = np.random.randint(1, 100, 10)
arr

array([30, 76,  4, 83, 82, 13, 23, 97, 91, 67])

In [67]:
arr + 2

array([32, 78,  6, 85, 84, 15, 25, 99, 93, 69])

In [68]:
arr - 2

array([28, 74,  2, 81, 80, 11, 21, 95, 89, 65])

In [69]:
arr * 2

array([ 60, 152,   8, 166, 164,  26,  46, 194, 182, 134])

### Logic

In [70]:
arr

array([30, 76,  4, 83, 82, 13, 23, 97, 91, 67])

In [71]:
arr > 20

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True])

In [72]:
arr == 97

array([False, False, False, False, False, False, False,  True, False,
       False])

In [73]:
arr[arr>20]

array([30, 76, 83, 82, 23, 97, 91, 67])

In [74]:
arr[arr<20]

array([ 4, 13])

In [75]:
np.logical_and(arr<50, arr>10)

array([ True, False, False, False, False,  True,  True, False, False,
       False])

In [76]:
result = np.logical_and(arr<50, arr>10)

In [77]:
arr[result]

array([30, 13, 23])

In [79]:
np.array([list(filter(lambda x: x < 50 and x > 10, arr))])

array([[30, 13, 23]])